builtin/builtin.go, builtin/tests/builtin.py, py/object.go
Hi, I have highly interested in this project.
I've experienced to work on the grumpy project also.
Anyway, this might be my first PR, Please take a look.
=> builtin: Implement builtin function any, all.

builtin/builtin.go, builtin/tests/builtin.py
Update builtin_all and builtin_any for Python3
reference:
- https://docs.python.org/3/library/functions.html#all
- https://docs.python.org/3/library/functions.html#any
Fixes: https://github.com/go-python/gpython/issues/14
=> builtin: Update builtin_all and builtin_any for Python3

.travis.yml, go.mod, go.sum
This CL bumps `go.mod` to use peterh/liner@v1.1.0.
Also really test Go modules by enabling `GO111MODULE=on`, only for `master`.
=> gpython: use peterh/liner@v1.1.0

builtin/builtin.go, builtin/tests/builtin.py, py/string.go
=> builtin: Implement builtin sum

builtin/builtin.go
see https://github.com/go-python/gpython/issues/24
=> print should use __str__ or __repr__ when available

py/complex.go, py/tests/complex.py
Implement https://github.com/go-python/gpython/issues/30 and add missing properties and methods
(real, imag, conjgate).
Also added tests.
=> Added __str__ and __repr__ plus missing properties 

py/exception.go
=> py: Fix TracebackDump not to dump duplicated exception type

py/sequence.go, vm/tests/generators.py
Sequence.Iterate does not handle exceptions.
Iterate() should return error except StopIteration.
Fixes: https://github.com/go-python/gpython/issues/32
=> py: Fix errors are suppressed in generator comprehensions

py/range.go, py/tests/range.py
=> py: Support __len__ of rangetype.

builtin/builtin.go, builtin/tests/builtin.py, py/enumerate.go, py/tests/list.py
Now, gpython supports enumerate feature
=> builtin: Implement enumerate feature

py/range.go, py/tests/range.py
=> py: Fix range to support negative step

builtin/builtin.go, builtin/tests/builtin.py, py/tests/zip.py, py/zip.go
=> py: Support zip builtin feature

py/range.go, py/tests/range.py
=> py: Implement range M__getitem__

pytest/pytest.go, vm/benchmarks/fib.py, vm/benchmarks/fibtc.py, vm/vm_test.go
This reworks the existing test framework so it can be used for
benchmarks too.  Note that it now uses the subtest framework which
makes the test output much neater.
To run the benchmarks use
cd vm
go test -v -run XXX -bench .
Fixes #50
=> Implement benchmark framework for gpython along with a couple of benchmarks

builtin/builtin.go, builtin/tests/builtin.py, py/args.go
- Implement builtin min/max function
- Support the keyword-only option for `ParseTupleAndKeywords`
=> builtin: Implement min/max builtin function

builtin/builtin.go, builtin/tests/builtin.py, py/call_iterator.go, py/tests/iter.py
- Implement CallIterator
- Implement builtin iter()
Closes: #53
=> builtin: Implement builtin_iter

builtin/builtin.go, builtin/tests/builtin.py
I've implemented delattr for builtin function.
=> builtin: Implement delattr

py/classmethod.go, py/function.go, py/staticmethod.go, py/tests/classmethod.py, py/tests/function.py, py/tests/staticmethod.py
Add test files for function, staticmethod and classmethod
Fixes #56
=> Fix initialisation of function, staticmethod and classmethod __dict__

py/string.go, py/tests/string.py
Added `split` method to str:
```
>>> "hello|world".split("|")
['hello', 'world']
```
=> Adding split method to string class

py/dict.go, py/tests/dict.py
=> Adding iterator method to Dict

py/list.go, py/string.go, py/tests/list.py, py/tests/string.py
This PR adds
- `string.startswith`
- `string.endswith`
- `list.append`
- `list.extend`
=> String and List Methods

repl/cli/cli.go
Now when the ~/.gpyhistory file does not exist, do not show the error
message in the repl, as long as this does not disrupt the experience in the repl.
Fixes go-python/gpython#62.
=> fix: ~/.gpyhistory: no such file or directory

py/dict.go, py/tests/dict.py
Implement __contains__ of dict for better performance.
ISSUE: #58
=> dict: Implement __contains__ of dict

py/list.go, py/tests/list.py, py/tests/tuple.py, py/tuple.go
py: Fix __mul__ of list and tuple on negative case
=> py: Fix __mul__ of list and tuple on negative case

builtin/builtin.go, builtin/tests/builtin.py, py/string.go
=> builtin: Implement builtin_ascii

py/set.go, py/tests/set.py
=> Implement and of set

py/set.go, py/tests/set.py
Implement __or__ of set
ISSUE: #76
=> set: Implement __or__ of set

py/range.go, py/range_repr110.go, py/range_repr19.go, py/tests/range.py
Implement `__repr__`, `__str__`, `__eq__`, `__ne__` of range
Fixes #86
=> Implement range object

py/set.go, py/tests/set.py
=> set: Implement __sub__ and __xor__ of set

builtin/builtin.go, builtin/tests/builtin.py
line 190 to 193.
I tried to apply the end option to the print function.
Added code performed when "end" value of parameter "kwargs" is not "nil".
=> Fix "end" option in print func

py/internal.go, py/range.go, py/tests/range.py
Crate a new range object by calculating start,
stop, and step when slice is entered as argument
to the __getitem__ function of the range
Fixes #77
=> Add Slice function for range type

builtin/builtin.go, builtin/tests/builtin.py
Reverts go-python/gpython#90
Sorry guys, I didn't review the patch #90 well.
The patch was not the proper approach.
=> Revert "Fix "end" option in print func"

repl/repl.go, repl/repl_test.go
Before this change, entering a comment in the REPL caused the REPL to
read the comment indefinitely effectively breaking it.
After this change the behaviour should be exactly the same as python3/
=> Fix comments in REPL - fixes #78

py/sequence.go, py/set.go, py/tests/set.py
Implement the initialization of Set with a sequence. looked up the implementation of the List
issue #76
=> set: Implement initialization set with sequence

builtin/builtin.go, py/slice.go, py/tests/slice.py
=> Add __new__ function and property of slice

py/internal.go, py/range.go, py/tests/list.py, py/tests/range.py, py/tests/string.py, py/tests/tuple.py
Generate TypeError when __index__ return non-integer value
Fixes #96
=> Handle the non-integer return of __index__

py/float.go, py/tests/float.py
=> Implement float is_integer method

py/dict.go, py/tests/dict.py
Implement the "get" function and add unit test.
fixes #105
=> Implementing the "get" function on a "Dictionary"

py/set.go, py/tests/set.py
if type of other is not set, 
return NotImplemented
=> __ne__ of set return NotImplemented 

py/bool.go, py/slice.go, py/tests/slice.py
=> Implement eq, ne for slice

builtin/builtin.go, vm/tests/builtin.py, vm/tests/libtest.py
=> Implement isinstance

py/dict.go, py/tests/dict.py
=> Fix bug in "items" function

.gitignore, builtin/tests/builtin.py, py/args.go
This expands and restores testing for print with keyword args, exposing bugs in `py.ParseTupleAndKeywords()`
Accompanied with additional PR to merge branch `hotfix-parse-kwargs`
=> kwarg testing (exposes bugs in py.ParseTupleAndKeywords)

builtin/builtin.go, compile/compile.go, compile/instructions_test.go, marshal/marshal.go, parser/stringescape.go, py/bytes.go, py/code.go, py/int.go, py/method.go, py/range.go, py/string.go, vm/eval.go
Inserted non-affecting changes to resolve Go warnings
=> resolved benign Go warnings

examples/embedding/lib/REPL-startup.py, examples/embedding/lib/mylib.py, examples/embedding/main_test.go, examples/embedding/mylib-demo.py, examples/multi-context/main.go, main.go, main_test.go, testdata/hello.py, testdata/hello_golden.txt
Signed-off-by: Sebastien Binet <binet@cern.ch>
=> examples/{embedding,multi-context}: add LICENSE blurb, cosmetics

examples/embedding/main.go, examples/embedding/mylib.module.go, examples/embedding/testdata/embedding_out_golden.txt, examples/multi-context/main.go, main.go
added proper py.Context.Close() for completeness and added as test for `examples/embedding`
=> proper example completeness

py/dict.go, py/tests/dict.py
Old behavior:
len({"a" : 1, "b" : 2})
```
TypeError: "object of type 'dict' has no len()"
```
New behavior returns the number of elements in the dict
=> Adding missing __len__ method to dict objects

repl/repl_test.go
This CL reverts the display of want/got into got/want in order to
follow good Go practices.
Also align got/want display so as to ease deciphering the error
for normal humans.
Signed-off-by: Sebastien Binet <binet@cern.ch>
=> repl: reorder want/got into got/want

.github/workflows/ci.yml, CONTRIBUTE.md, README.md, examples/embedding/README.md
Signed-off-by: Sebastien Binet <binet@cern.ch>
=> all: rename master into main

py/dict.go, py/tests/dict.py
Enables the 'del' command to delete items from a dict
=> Adding __delitem__ to dict

parser/lexer.go, parser/lexer_test.go
The python file on the Windows platform may be in CRLF format. For example, git may convert the file to CRLF under Windows, resulting in parsing failure
=> parser: fix CRLF(\r\n) file parsing error, SyntaxError: 'invalid syntax'

py/arithmetic.go, py/dict.go, py/exception.go, py/filter.go, py/gen.go, py/internal.go, py/iterator.go, py/list.go, py/map.go, py/object.go, py/tests/filter.py, py/tests/iter.py, py/tests/map.py, py/type.go, stdlib/builtin/builtin.go, stdlib/builtin/tests/builtin.py
Python-3.4.9/Doc/c-api/iterator.rst
> Python provides two general-purpose iterator objects.  The first, a sequence
iterator, works with an arbitrary sequence supporting the :meth:`__getitem__`
method.  The second works with a callable object and a sentinel value, calling
the callable for each item in the sequence, and ending the iteration when the
sentinel value is returned.
`Python-3.4.9/Lib/test/test_builtin.py`
```python
class Squares:
def __init__(self, max):
self.max = max
self.sofar = []
def __len__(self): return len(self.sofar)
def __getitem__(self, i):
if not 0 <= i < self.max: raise IndexError
n = len(self.sofar)
while n <= i:
self.sofar.append(n*n)
n += 1
return self.sofar[i]
```
In CPython, `Squares (5)` is an iterable object, and to support this type of iterable object, I made …
=> all: fix iterable object, implement `filter`, `map`, `oct` and optimise `hex`

compile/compile.go, py/code.go, vm/tests/class.py, vm/tests/decorators.py, vm/tests/functions.py, vm/tests/libtest.py
After several hours of reading the Python source code, it was found that the closure issue was only caused by the lack of assignment to `Code.Cell2arg`
The submission still requires some optimization, and I will complete it in the near future. If possible, I would also like to receive some coding suggestions
=> compile,py: fix closure and decorator

stdlib/sys/sys.go
`os.Executable()` is not implemented in "js" and "wasip1" targets in current Golang versions, so WASM builds encounter `Executable not implemented for js` errors in runtime.
This fix is borrowed from Brad's https://github.com/tailscale/tailscale/pull/8325 .
=> Fixed WASM compatibility by avoiding panic due to absence of `os.Executable()`

main.go, py/type.go
=> py: Fix automatic addition of __doc__ to dict object (#229)

py/string.go, py/string_test.go, py/tests/string.py
add lower() and upper for py str
Updates #232
=> add lower() and upper for py str feat:(#232)

py/import.go
Currently gpython can't handle import on Windows because it's using `path` to handle file paths, which only support OSes which use `/` as path separator:
```
PS C:\Users\xxxxx\Source\gpython> go run . py\tests\string.py
Traceback (most recent call last):
File "C:\\Users\\xxxxx\\Source\\gpython/py\\tests\\string.py", line 5, in <module>
FileNotFoundError: 'Failed to resolve "libtest"'
exit status 1
```
Using `path/filepath` can fix it.
=> py: fix import on Windows

py/exception.go, vm/tests/exceptions.py
Support create `Exception` instance with multiple non-str arguments.
=> py: fix exception repr

main.go, repl/cli/cli.go, repl/repl.go, stdlib/sys/sys.go
Currently `raise SystemExit()` or calling `sys.exit()` is not handled correctly. The interpreter will crash because `Exception.__repr__` can't handle `SystemExit`, but #242 will fix this. So we should handle the `SystemExit` and exit the interpreter.
=> all: handle SystemExit
